#Hugo configuration
title = "qweasd"
baseURL = "https:\/\/qwew.asd.dds"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
